//====================================================================================================
// Base code generated with LeatherGoods - ASF.Services.Http
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ASF.Business;
using ASF.Entities;
using ASF.Services.Contracts;
using ASF.Services.Contracts.Responses;

namespace ASF.Services.Http
{
    /// <summary>
    /// OrderNumber HTTP service controller.
    /// </summary>
    [RoutePrefix("rest/OrderNumber")]
    public class OrderNumberService : ApiController
    {

        [HttpPost]
        [Route("Add")]
        public OrderNumber Add(OrderNumber orderNumber)
        {
            try
            {
                var bo = new OrderNumberBusiness();
                return bo.Add(orderNumber);
            }
            catch (Exception ex)
            {
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        [HttpGet]
        [Route("All")]
        public AllOrderNumberResponse All()
        {
            try
            {
                var response = new AllOrderNumberResponse();
                var bo = new OrderNumberBusiness();
                response.Result = bo.All();
                return response;
            }
            catch (Exception ex)
            {
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        [HttpPost]
        [Route("Edit")]
        public void Edit(OrderNumber orderNumber)
        {
            try
            {
                var bo = new OrderNumberBusiness();
                orderNumber.ChangedOn = System.DateTime.Now;
                bo.Edit(orderNumber);
            }
            catch (Exception ex)
            {
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        [HttpGet]
        [Route("Find")]
        public FindOrderNumberResponse Find(int id)
        {
            try
            {
                var response = new FindOrderNumberResponse();
                var bo = new OrderNumberBusiness();
                response.Result = bo.Find(id);
                return response;
            }
            catch (Exception ex)
            {
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        [HttpGet]
        [Route("Remove")]
        public void Remove(int id)
        {
            try
            {
                var bo = new OrderNumberBusiness();
                bo.Remove(id);
            }
            catch (Exception ex)
            {
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

    }
}
