//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    /// <summary>
    /// OrderBusiness business component.
    /// </summary>
    public class OrderBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="order"></param>
        /// <returns></returns>
        public Order Add(Order order)
        {
            var orderDac = new OrderDAC();
            var neworder = new Order();
            neworder = orderDac.Create(order);

            var cartbusi = new CartItemBusiness();
            var lista = cartbusi.FindByCartId(neworder.OrderNumber);

            var odb = new OrderDetailBusiness();

            foreach (CartItem item in lista)
            {
                var od = new OrderDetail();
                od.OrderId = neworder.Id;
                od.ProductId = item.ProductId;
                od.Price = item.Price;
                od.Quantity = item.Quantity;
                odb.Add(od);
            }
            return neworder;
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var orderDac = new OrderDAC();
            orderDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<Order> All()
        {
            var orderDac = new OrderDAC();
            var result = orderDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Order Find(int id)
        {
            var orderDac = new OrderDAC();
            var result = orderDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="order"></param>
        public void Edit(Order order)
        {
            var orderDac = new OrderDAC();
            orderDac.UpdateById(order);
        }

        public Order FindByOrder(int order)
        {
            var orderDac = new OrderDAC();
            var result = orderDac.SelectByOrder(order);
            return result;
        }
    }
}
